name: Deploy to development
env:
  tf_version: '1.11.3'
  tg_version: '0.76.8'
  tf_working_dir: '.'

on:
    push:
        branches:
            - main

jobs:
    terragrunt:
        name: 'Terragrunt'
        runs-on: 'self-hosted'
    
        steps:
            - name: Checlout
              uses: actions/checkout@master
            
            - name: 'Terragrunt Init'
              uses: the-commons-project/terragrunt-github-actions@master
              with:
                tf_actions_version: ${{ env.tf_version }}
                tg_actions_version: ${{ env.tg_version }}
                tf_actions_subcommand: 'init'
                tf_actions_working_dir: ${{ env.tf_working_dir }}
                tf_actions_comment: true
                
            - name: 'Terragrunt Plan'
              uses: the-commons-project/terragrunt-github-actions@master
              with:
                tf_actions_version: ${{ env.tf_version }}
                tg_actions_version: ${{ env.tg_version }}
                tf_actions_subcommand: 'plan'
                tf_actions_working_dir: ${{ env.tf_working_dir }}
                tf_actions_comment: true