name: Deploy to development
env:
  environment: 'development'

on:
    push:
        branches:
            - main

jobs:
    terragrunt:
        name: 'Terragrunt'
        runs-on: 'self-hosted'
    
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: 'Terragrunt Init'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && terragrunt init
              shell: bash

            - name: 'Terragrunt Plan'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && terragrunt plan
              shell: bash              