name: Deploy to development

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: 'self-hosted'
    
        steps:
            - name: Checlout
              uses: actions/checkout@v2