name: Deploy to development
env:
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
      branches: [ main, development ]

jobs:
    terragrunt:
        name: 'Terragrunt'
        runs-on: 'self-hosted'
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: 'Terragrunt Init'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && terragrunt init
              shell: bash

            - name: 'Terragrunt Plan'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && terragrunt plan
              shell: bash              