name: On Push Request
env:
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
      branches: [ main, development ]

jobs:
    plan:
        name: 'Terragrunt preparation'
        runs-on: 'self-hosted'
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Echo environment
              run: echo "Using environment [${environment}]"
              shell: bash

            - name: 'TFLint init'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && tflint --init
              shell: bash              

            - name: 'TFSec execution'
              run: cd ${GITHUB_WORKSPACE} && tfsec --force-all-dirs --exclude-downloaded-modules --soft-fail -f lovely
              shell: bash

            - name: Checkout PR branch
              run: |
                git fetch origin ${{ github.event.pull_request.head.ref }}
                git checkout ${{ github.event.pull_request.head.ref }}

            - name: 'Looking for GIT Leaks'
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Terragrunt Plan'
              run: cd ${GITHUB_WORKSPACE}/environments/${environment} && terragrunt run-all plan
              shell: bash              